# Generated by Django 3.0.3 on 2020-03-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=500)),
                ('linkedin_url', models.TextField(blank=True, max_length=1500)),
                ('certifications', models.TextField(blank=True)),
                ('current_job', models.TextField(blank=True, max_length=500)),
                ('companies', models.TextField(blank=True)),
                ('is_updated', models.BooleanField(default=False)),
            ],
        ),
    ]
